### ISSUE TITLE
Elevation problem in Flexible Space Example

### ISSUE THREAD

**Issue by petrnohejl** [saulmm/CoordinatorExamples#2]
When you update support libraries to 24.0.0, Flexible Space Example will stop working properly. If you scroll fast, the CardView will be displayed under the AppBarLayout for some time which makes annoying snatchy effect. I think it might have something to do with the elevation of CardView and AppBarLayout. It seems that it is working well on older versions of support libraries. See attached video.

![device-2016-06-29-150251](https://cloud.githubusercontent.com/assets/552213/16453589/a2d7933c-3e0d-11e6-8430-a1a578a6c6d9.gif)

**Comment by petrnohejl** [comment]
I found a solution. You just have to explicitly define elevation for AppBarLayout like this:

```
<android.support.design.widget.AppBarLayout
    ...
    app:elevation="1dp">
```

**Comment by saulmm** [comment]
The project is now using the `25.3.0` version of the design library, I couldn't reproduce it.
