### ISSUE TITLE
pulldown pre scroll issue in MaterialUpConceptActivity

### ISSUE THREAD

**Issue by chefish** [saulmm/CoordinatorExamples#4]
In MaterialUpConceptActivity，the scroll flag of Toolbar is "scroll|enterAlways|snap"，so it should be pulled down before RecyclerView scroll, but there is a layout_marginTop in Toolbar,it make Toolbar only be pulled partly.I think we should remove the layout_marginTop in Toolbar.Instead we can add "android:layout_marginBottom="-48dp""  in CircleImageView

**Comment by saulmm** [comment]
Yep, you were true, I removed that useless margin from the toolbar and anchored the ImageView to the top of the linear layout with the texts.

Thank you!
